### ISSUE TITLE
Filtered terms

### ISSUE THREAD

**Issue by nirgn975** [hasadna/open_pension#142]
A list of filtered terms.

- [ ] Create a `json` file, with the list data.
- [ ] Create the component (named `op-filter-by-level`).
- [ ] Inject the component on the `op` (root) component (this will show your component on the main page).
- [ ] Create a service to get the data from the file.
- [ ] Show the terms as a list.

The list:
```
managing_body
asset_type
instrument_sub_type
instrument_type
liquidity
activity_industry
currency
rating_agency
reference_index
rating
underlying_asset
instrument_name
```

**Comment by ofekd** [comment]
@nirgn975 should I branch off of master? It has a build error:

```
Error: Typescript found the following errors:
  /www/app/tmp/broccoli_type_script_compiler-input_base_path-33f2QDwz.tmp/0/src/app/companies/companies-grid/companies-grid.component.spec.ts (10, 21): Supplied parameters do not match any signature of call target.
  /www/app/tmp/broccoli_type_script_compiler-input_base_path-33f2QDwz.tmp/0/src/app/op.component.spec.ts (18, 18): Property 'title' does not exist on type 'OpComponent'.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (/www/app/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:120:19)
    at BroccoliTypeScriptCompiler.build (/www/app/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:43:10)
    at /www/app/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/www/app/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/www/app/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/www/app/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/www/app/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at BroccoliTypeScriptCompiler.Plugin (/www/app/node_modules/angular-cli/node_modules/broccoli-plugin/index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (/www/app/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at BroccoliTypeScriptCompiler (/www/app/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:27:5)
    at Angular2App._getTsTree (/www/app/node_modules/angular-cli/lib/broccoli/angular2-app.js:331:18)
    at Angular2App._buildTree (/www/app/node_modules/angular-cli/lib/broccoli/angular2-app.js:124:23)
    at new Angular2App (/www/app/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/www/app/angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/www/app/node_modules/angular-cli/node_modules/ember-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/www/app/node_modules/angular-cli/node_modules/ember-cli/lib/models/builder.js:89:10)
    at new Class (/www/app/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/www/app/node_modules/angular-cli/node_modules/ember-cli/lib/tasks/serve.js:15:19)
    at /www/app/node_modules/angular-cli/node_modules/ember-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/www/app/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/www/app/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /www/app/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/www/app/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
```

**Comment by nirgn975** [comment]
Delete the `op.component.spec.ts` file, but don't `commit` it on your PR.

**Comment by ofekd** [comment]
@nirgn975 Thanks, got it working. A couple of questions:

1. Is it reasonable to have the filter component receive an items promise from the parent component? That way it can be shared across the app, beyond the pi usage.
2. The result is currently an array with selected items. Is that format fine for the consumer?

**Comment by nirgn975** [comment]
@ofekd 
1. Work with `Observable` and not `promise`. It should get it from a service (that's sit in the root `shared` directory - that way everyone can use this service). And all our website should be the pi. There is not much else, so he is the main and only component that will use this list.

2. Array with selected items sounds good. Just make sure you get them from a json (create a dummy one in `data` directory) with a service. That should be enough for this PR.

By the way, even if it's not finish do a PR and add `WIP` in the header. Like: `WIP: yourTitle` (stands for Work In Progress). That way I can see the code and help, see if you're on the right track, and understand that it's not final and it's in progress..

**Comment by ofekd** [comment]
@nirgn975 I need proper select[multiple] binding for this. It's broken in rc.4 and was fixed in rc.5 (see angular/angular#9784). Can I migrate the open_pension client app?
